program prueba
    [* En este programa (que viene a ser una copia casi exacta de la prueba valida nº4) se comprueba que al añadir un exit fuera del bucle, el compilador nos indicará que
    por medio de un mensaje de error que tenemos un exit fuera del bucle, sin escribirnos el codigo intermedio*]
    int p;
    int a;

    {
    p = 2;
    a = 0;
    for (int i = 0; i < 5; i = i +3){
        a = a + 1;
        for (int j = 0; j < i; j = j +1){
            p = p + 5;
        };
        if p < i and a > p {
            p = p/a;
            exit;
        };
    };
    exit;
    println(p);
    println(a);
    }